/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ted_jnihandleimage_JniHandle */

#ifndef _Included_com_ted_jnihandleimage_JniHandle
#define _Included_com_ted_jnihandleimage_JniHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ted_jnihandleimage_JniHandle
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ted_jnihandleimage_JniHandle_test
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL
Java_com_ted_jnihandleimage_JniHandle_convertToGray(JNIEnv *env, jobject instance, jobject bitmapIn,
                                                    jobject bitmapOut);

JNIEXPORT void JNICALL
        Java_com_ted_jnihandleimage_JniHandle_changeBright(JNIEnv *env, jobject instance, jobject bitmap,
                                                           jint type);

#ifdef __cplusplus
}
#endif
#endif
